package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"crm-communication-api/graph/generated"
	model1 "crm-communication-api/graph/model"
	"crm-communication-api/internal/model"
	"fmt"
)

// ID is the resolver for the id field.
func (r *clientResolver) ID(ctx context.Context, obj *model.Client) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *clientResolver) CreatedAt(ctx context.Context, obj *model.Client) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *clientResolver) UpdatedAt(ctx context.Context, obj *model.Client) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ID is the resolver for the id field.
func (r *conversationResolver) ID(ctx context.Context, obj *model.Conversation) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ClientID is the resolver for the clientId field.
func (r *conversationResolver) ClientID(ctx context.Context, obj *model.Conversation) (*string, error) {
	panic(fmt.Errorf("not implemented: ClientID - clientId"))
}

// Participants is the resolver for the participants field.
func (r *conversationResolver) Participants(ctx context.Context, obj *model.Conversation) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Participants - participants"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *conversationResolver) CreatedAt(ctx context.Context, obj *model.Conversation) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *conversationResolver) UpdatedAt(ctx context.Context, obj *model.Conversation) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ID is the resolver for the id field.
func (r *emailResolver) ID(ctx context.Context, obj *model.Email) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Received is the resolver for the received field.
func (r *emailResolver) Received(ctx context.Context, obj *model.Email) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: Received - received"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *emailResolver) CreatedAt(ctx context.Context, obj *model.Email) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// ID is the resolver for the id field.
func (r *emailTemplateResolver) ID(ctx context.Context, obj *model.EmailTemplate) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *emailTemplateResolver) CreatedAt(ctx context.Context, obj *model.EmailTemplate) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *emailTemplateResolver) UpdatedAt(ctx context.Context, obj *model.EmailTemplate) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ID is the resolver for the id field.
func (r *messageResolver) ID(ctx context.Context, obj *model.Message) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Mentions is the resolver for the mentions field.
func (r *messageResolver) Mentions(ctx context.Context, obj *model.Message) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Mentions - mentions"))
}

// ReadBy is the resolver for the readBy field.
func (r *messageResolver) ReadBy(ctx context.Context, obj *model.Message) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: ReadBy - readBy"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *messageResolver) CreatedAt(ctx context.Context, obj *model.Message) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model1.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// GoogleLogin is the resolver for the googleLogin field.
func (r *mutationResolver) GoogleLogin(ctx context.Context, code string) (*model1.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: GoogleLogin - googleLogin"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model1.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model1.NewUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// CreateClient is the resolver for the createClient field.
func (r *mutationResolver) CreateClient(ctx context.Context, input model1.NewClientInput) (*model.Client, error) {
	panic(fmt.Errorf("not implemented: CreateClient - createClient"))
}

// CreateConversation is the resolver for the createConversation field.
func (r *mutationResolver) CreateConversation(ctx context.Context, input model1.NewConversationInput) (*model.Conversation, error) {
	panic(fmt.Errorf("not implemented: CreateConversation - createConversation"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model1.NewMessageInput) (*model.Message, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// SendEmail is the resolver for the sendEmail field.
func (r *mutationResolver) SendEmail(ctx context.Context, input model1.NewEmailInput) (*model.Email, error) {
	panic(fmt.Errorf("not implemented: SendEmail - sendEmail"))
}

// SendEmailWithTemplate is the resolver for the sendEmailWithTemplate field.
func (r *mutationResolver) SendEmailWithTemplate(ctx context.Context, input model1.NewEmailWithTemplateInput) (*model.Email, error) {
	panic(fmt.Errorf("not implemented: SendEmailWithTemplate - sendEmailWithTemplate"))
}

// SyncGmail is the resolver for the syncGmail field.
func (r *mutationResolver) SyncGmail(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: SyncGmail - syncGmail"))
}

// CreateEmailTemplate is the resolver for the createEmailTemplate field.
func (r *mutationResolver) CreateEmailTemplate(ctx context.Context, input model1.NewEmailTemplateInput) (*model.EmailTemplate, error) {
	panic(fmt.Errorf("not implemented: CreateEmailTemplate - createEmailTemplate"))
}

// UpdateEmailTemplate is the resolver for the updateEmailTemplate field.
func (r *mutationResolver) UpdateEmailTemplate(ctx context.Context, id string, input model1.UpdateEmailTemplateInput) (*model.EmailTemplate, error) {
	panic(fmt.Errorf("not implemented: UpdateEmailTemplate - updateEmailTemplate"))
}

// DeleteEmailTemplate is the resolver for the deleteEmailTemplate field.
func (r *mutationResolver) DeleteEmailTemplate(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteEmailTemplate - deleteEmailTemplate"))
}

// MarkMessageAsRead is the resolver for the markMessageAsRead field.
func (r *mutationResolver) MarkMessageAsRead(ctx context.Context, messageID string) (bool, error) {
	panic(fmt.Errorf("not implemented: MarkMessageAsRead - markMessageAsRead"))
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model1.NewTaskInput) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: CreateTask - createTask"))
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model1.UpdateTaskInput) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: UpdateTask - updateTask"))
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTask - deleteTask"))
}

// CreateReminder is the resolver for the createReminder field.
func (r *mutationResolver) CreateReminder(ctx context.Context, input model1.NewReminderInput) (*model.Reminder, error) {
	panic(fmt.Errorf("not implemented: CreateReminder - createReminder"))
}

// UpdateReminder is the resolver for the updateReminder field.
func (r *mutationResolver) UpdateReminder(ctx context.Context, id string, input model1.UpdateReminderInput) (*model.Reminder, error) {
	panic(fmt.Errorf("not implemented: UpdateReminder - updateReminder"))
}

// DeleteReminder is the resolver for the deleteReminder field.
func (r *mutationResolver) DeleteReminder(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteReminder - deleteReminder"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// Clients is the resolver for the clients field.
func (r *queryResolver) Clients(ctx context.Context) ([]*model.Client, error) {
	panic(fmt.Errorf("not implemented: Clients - clients"))
}

// Client is the resolver for the client field.
func (r *queryResolver) Client(ctx context.Context, id string) (*model.Client, error) {
	panic(fmt.Errorf("not implemented: Client - client"))
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID string) ([]*model.Message, error) {
	panic(fmt.Errorf("not implemented: Messages - messages"))
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context) ([]*model.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversations - conversations"))
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*model.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversation - conversation"))
}

// Emails is the resolver for the emails field.
func (r *queryResolver) Emails(ctx context.Context, clientID string) ([]*model.Email, error) {
	panic(fmt.Errorf("not implemented: Emails - emails"))
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, clientID string) ([]*model.TimelineEvent, error) {
	panic(fmt.Errorf("not implemented: Timeline - timeline"))
}

// EmailTemplates is the resolver for the emailTemplates field.
func (r *queryResolver) EmailTemplates(ctx context.Context) ([]*model.EmailTemplate, error) {
	panic(fmt.Errorf("not implemented: EmailTemplates - emailTemplates"))
}

// EmailTemplate is the resolver for the emailTemplate field.
func (r *queryResolver) EmailTemplate(ctx context.Context, id string) (*model.EmailTemplate, error) {
	panic(fmt.Errorf("not implemented: EmailTemplate - emailTemplate"))
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: Tasks - tasks"))
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: Task - task"))
}

// Reminders is the resolver for the reminders field.
func (r *queryResolver) Reminders(ctx context.Context) ([]*model.Reminder, error) {
	panic(fmt.Errorf("not implemented: Reminders - reminders"))
}

// ID is the resolver for the id field.
func (r *reminderResolver) ID(ctx context.Context, obj *model.Reminder) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// RemindAt is the resolver for the remindAt field.
func (r *reminderResolver) RemindAt(ctx context.Context, obj *model.Reminder) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: RemindAt - remindAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *reminderResolver) CreatedAt(ctx context.Context, obj *model.Reminder) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// MessageReceived is the resolver for the messageReceived field.
func (r *subscriptionResolver) MessageReceived(ctx context.Context, conversationID string) (<-chan *model.Message, error) {
	panic(fmt.Errorf("not implemented: MessageReceived - messageReceived"))
}

// ID is the resolver for the id field.
func (r *taskResolver) ID(ctx context.Context, obj *model.Task) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// DueDate is the resolver for the dueDate field.
func (r *taskResolver) DueDate(ctx context.Context, obj *model.Task) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: DueDate - dueDate"))
}

// CompletedAt is the resolver for the completedAt field.
func (r *taskResolver) CompletedAt(ctx context.Context, obj *model.Task) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CompletedAt - completedAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *taskResolver) CreatedAt(ctx context.Context, obj *model.Task) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *taskResolver) UpdatedAt(ctx context.Context, obj *model.Task) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ID is the resolver for the id field.
func (r *timelineEventResolver) ID(ctx context.Context, obj *model.TimelineEvent) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// EventTime is the resolver for the eventTime field.
func (r *timelineEventResolver) EventTime(ctx context.Context, obj *model.TimelineEvent) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: EventTime - eventTime"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *timelineEventResolver) CreatedAt(ctx context.Context, obj *model.TimelineEvent) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *timelineEventResolver) UpdatedAt(ctx context.Context, obj *model.TimelineEvent) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *model.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *model.User) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *model.User) (*model1.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Client returns generated.ClientResolver implementation.
func (r *Resolver) Client() generated.ClientResolver { return &clientResolver{r} }

// Conversation returns generated.ConversationResolver implementation.
func (r *Resolver) Conversation() generated.ConversationResolver { return &conversationResolver{r} }

// Email returns generated.EmailResolver implementation.
func (r *Resolver) Email() generated.EmailResolver { return &emailResolver{r} }

// EmailTemplate returns generated.EmailTemplateResolver implementation.
func (r *Resolver) EmailTemplate() generated.EmailTemplateResolver { return &emailTemplateResolver{r} }

// Message returns generated.MessageResolver implementation.
func (r *Resolver) Message() generated.MessageResolver { return &messageResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Reminder returns generated.ReminderResolver implementation.
func (r *Resolver) Reminder() generated.ReminderResolver { return &reminderResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// Task returns generated.TaskResolver implementation.
func (r *Resolver) Task() generated.TaskResolver { return &taskResolver{r} }

// TimelineEvent returns generated.TimelineEventResolver implementation.
func (r *Resolver) TimelineEvent() generated.TimelineEventResolver { return &timelineEventResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type clientResolver struct{ *Resolver }
type conversationResolver struct{ *Resolver }
type emailResolver struct{ *Resolver }
type emailTemplateResolver struct{ *Resolver }
type messageResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type reminderResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type taskResolver struct{ *Resolver }
type timelineEventResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
