// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"crm-communication-api/internal/model"
)

type AuthPayload struct {
	AccessToken  string      `json:"accessToken"`
	RefreshToken string      `json:"refreshToken"`
	User         *model.User `json:"user"`
}

type Mutation struct {
}

type NewClientInput struct {
	Name    string  `json:"name"`
	Email   string  `json:"email"`
	Company *string `json:"company,omitempty"`
}

type NewConversationInput struct {
	Type     string   `json:"type"`
	Name     *string  `json:"name,omitempty"`
	ClientID *string  `json:"clientId,omitempty"`
	UserIds  []string `json:"userIds"`
}

type NewEmailInput struct {
	From    string   `json:"from"`
	To      []string `json:"to"`
	Subject string   `json:"subject"`
	Body    string   `json:"body"`
}

type NewEmailTemplateInput struct {
	Name    string `json:"name"`
	Subject string `json:"subject"`
	Body    string `json:"body"`
}

type NewEmailWithTemplateInput struct {
	To           []string `json:"to"`
	TemplateID   string   `json:"templateId"`
	TemplateData JSON     `json:"templateData"`
}

type NewMessageInput struct {
	Content        string `json:"content"`
	ConversationID string `json:"conversationId"`
}

type NewReminderInput struct {
	Content  string `json:"content"`
	RemindAt Time   `json:"remindAt"`
}

type NewTaskInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	AssignedTo  string  `json:"assignedTo"`
	DueDate     *Time   `json:"dueDate,omitempty"`
	ClientID    *string `json:"clientId,omitempty"`
}

type NewUserInput struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Avatar   *string `json:"avatar,omitempty"`
	Role     *string `json:"role,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type UpdateEmailTemplateInput struct {
	Name    *string `json:"name,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Body    *string `json:"body,omitempty"`
}

type UpdateReminderInput struct {
	Content   *string `json:"content,omitempty"`
	RemindAt  *Time   `json:"remindAt,omitempty"`
	Triggered *bool   `json:"triggered,omitempty"`
}

type UpdateTaskInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	AssignedTo  *string `json:"assignedTo,omitempty"`
	DueDate     *Time   `json:"dueDate,omitempty"`
	Completed   *bool   `json:"completed,omitempty"`
	ClientID    *string `json:"clientId,omitempty"`
}
