package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"crm-communication-api/graph/generated"
	graphmodel "crm-communication-api/graph/model"
	dbmodel "crm-communication-api/internal/model"
	"fmt"
)

// ID is the resolver for the id field.
func (r *clientResolver) ID(ctx context.Context, obj *dbmodel.Client) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *clientResolver) CreatedAt(ctx context.Context, obj *dbmodel.Client) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *clientResolver) UpdatedAt(ctx context.Context, obj *dbmodel.Client) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ID is the resolver for the id field.
func (r *conversationResolver) ID(ctx context.Context, obj *dbmodel.Conversation) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Type is the resolver for the type field.
func (r *conversationResolver) Type(ctx context.Context, obj *dbmodel.Conversation) (dbmodel.ConversationType, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// ClientID is the resolver for the clientId field.
func (r *conversationResolver) ClientID(ctx context.Context, obj *dbmodel.Conversation) (*string, error) {
	panic(fmt.Errorf("not implemented: ClientID - clientId"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *conversationResolver) CreatedAt(ctx context.Context, obj *dbmodel.Conversation) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *conversationResolver) UpdatedAt(ctx context.Context, obj *dbmodel.Conversation) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Messages is the resolver for the messages field.
func (r *conversationResolver) Messages(ctx context.Context, obj *dbmodel.Conversation, pagination *graphmodel.PaginationInput) (*graphmodel.MessageConnection, error) {
	panic(fmt.Errorf("not implemented: Messages - messages"))
}

// JoinedAt is the resolver for the joinedAt field.
func (r *conversationParticipantResolver) JoinedAt(ctx context.Context, obj *dbmodel.ConversationParticipant) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: JoinedAt - joinedAt"))
}

// ID is the resolver for the id field.
func (r *emailResolver) ID(ctx context.Context, obj *dbmodel.Email) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ClientID is the resolver for the clientId field.
func (r *emailResolver) ClientID(ctx context.Context, obj *dbmodel.Email) (*string, error) {
	panic(fmt.Errorf("not implemented: ClientID - clientId"))
}

// UserID is the resolver for the userId field.
func (r *emailResolver) UserID(ctx context.Context, obj *dbmodel.Email) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// To is the resolver for the to field.
func (r *emailResolver) To(ctx context.Context, obj *dbmodel.Email) ([]string, error) {
	panic(fmt.Errorf("not implemented: To - to"))
}

// Cc is the resolver for the cc field.
func (r *emailResolver) Cc(ctx context.Context, obj *dbmodel.Email) ([]string, error) {
	panic(fmt.Errorf("not implemented: Cc - cc"))
}

// Bcc is the resolver for the bcc field.
func (r *emailResolver) Bcc(ctx context.Context, obj *dbmodel.Email) ([]string, error) {
	panic(fmt.Errorf("not implemented: Bcc - bcc"))
}

// SentAt is the resolver for the sentAt field.
func (r *emailResolver) SentAt(ctx context.Context, obj *dbmodel.Email) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: SentAt - sentAt"))
}

// ReceivedAt is the resolver for the receivedAt field.
func (r *emailResolver) ReceivedAt(ctx context.Context, obj *dbmodel.Email) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: ReceivedAt - receivedAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *emailResolver) CreatedAt(ctx context.Context, obj *dbmodel.Email) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *emailResolver) UpdatedAt(ctx context.Context, obj *dbmodel.Email) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ID is the resolver for the id field.
func (r *emailAttachmentResolver) ID(ctx context.Context, obj *dbmodel.EmailAttachment) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Size is the resolver for the size field.
func (r *emailAttachmentResolver) Size(ctx context.Context, obj *dbmodel.EmailAttachment) (int, error) {
	panic(fmt.Errorf("not implemented: Size - size"))
}

// DownloadURL is the resolver for the downloadUrl field.
func (r *emailAttachmentResolver) DownloadURL(ctx context.Context, obj *dbmodel.EmailAttachment) (*string, error) {
	panic(fmt.Errorf("not implemented: DownloadURL - downloadUrl"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *emailAttachmentResolver) CreatedAt(ctx context.Context, obj *dbmodel.EmailAttachment) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// ID is the resolver for the id field.
func (r *emailTemplateResolver) ID(ctx context.Context, obj *dbmodel.EmailTemplate) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *emailTemplateResolver) CreatedAt(ctx context.Context, obj *dbmodel.EmailTemplate) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *emailTemplateResolver) UpdatedAt(ctx context.Context, obj *dbmodel.EmailTemplate) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ID is the resolver for the id field.
func (r *messageResolver) ID(ctx context.Context, obj *dbmodel.Message) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ConversationID is the resolver for the conversationId field.
func (r *messageResolver) ConversationID(ctx context.Context, obj *dbmodel.Message) (string, error) {
	panic(fmt.Errorf("not implemented: ConversationID - conversationId"))
}

// Metadata is the resolver for the metadata field.
func (r *messageResolver) Metadata(ctx context.Context, obj *dbmodel.Message) (*graphmodel.JSON, error) {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *messageResolver) CreatedAt(ctx context.Context, obj *dbmodel.Message) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *messageResolver) UpdatedAt(ctx context.Context, obj *dbmodel.Message) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*graphmodel.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// GoogleLogin is the resolver for the googleLogin field.
func (r *mutationResolver) GoogleLogin(ctx context.Context, code string) (*graphmodel.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: GoogleLogin - googleLogin"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*graphmodel.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input graphmodel.NewUserInput) (*dbmodel.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// CreateClient is the resolver for the createClient field.
func (r *mutationResolver) CreateClient(ctx context.Context, input graphmodel.CreateClientInput) (*dbmodel.Client, error) {
	panic(fmt.Errorf("not implemented: CreateClient - createClient"))
}

// UpdateClient is the resolver for the updateClient field.
func (r *mutationResolver) UpdateClient(ctx context.Context, input graphmodel.UpdateClientInput) (*dbmodel.Client, error) {
	panic(fmt.Errorf("not implemented: UpdateClient - updateClient"))
}

// CreateConversation is the resolver for the createConversation field.
func (r *mutationResolver) CreateConversation(ctx context.Context, input graphmodel.CreateConversationInput) (*dbmodel.Conversation, error) {
	panic(fmt.Errorf("not implemented: CreateConversation - createConversation"))
}

// AddParticipant is the resolver for the addParticipant field.
func (r *mutationResolver) AddParticipant(ctx context.Context, conversationID string, userID string) (*dbmodel.ConversationParticipant, error) {
	panic(fmt.Errorf("not implemented: AddParticipant - addParticipant"))
}

// RemoveParticipant is the resolver for the removeParticipant field.
func (r *mutationResolver) RemoveParticipant(ctx context.Context, conversationID string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveParticipant - removeParticipant"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, conversationID string, content string) (*dbmodel.Message, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// MarkMessageAsRead is the resolver for the markMessageAsRead field.
func (r *mutationResolver) MarkMessageAsRead(ctx context.Context, messageID string) (bool, error) {
	panic(fmt.Errorf("not implemented: MarkMessageAsRead - markMessageAsRead"))
}

// SendEmail is the resolver for the sendEmail field.
func (r *mutationResolver) SendEmail(ctx context.Context, input graphmodel.SendEmailInput) (*dbmodel.Email, error) {
	panic(fmt.Errorf("not implemented: SendEmail - sendEmail"))
}

// SyncGmail is the resolver for the syncGmail field.
func (r *mutationResolver) SyncGmail(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: SyncGmail - syncGmail"))
}

// CreateEmailTemplate is the resolver for the createEmailTemplate field.
func (r *mutationResolver) CreateEmailTemplate(ctx context.Context, input graphmodel.CreateEmailTemplateInput) (*dbmodel.EmailTemplate, error) {
	panic(fmt.Errorf("not implemented: CreateEmailTemplate - createEmailTemplate"))
}

// UpdateEmailTemplate is the resolver for the updateEmailTemplate field.
func (r *mutationResolver) UpdateEmailTemplate(ctx context.Context, input graphmodel.UpdateEmailTemplateInput) (*dbmodel.EmailTemplate, error) {
	panic(fmt.Errorf("not implemented: UpdateEmailTemplate - updateEmailTemplate"))
}

// DeleteEmailTemplate is the resolver for the deleteEmailTemplate field.
func (r *mutationResolver) DeleteEmailTemplate(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteEmailTemplate - deleteEmailTemplate"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dbmodel.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*dbmodel.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filter *graphmodel.ClientFilterInput, pagination *graphmodel.PaginationInput) ([]*dbmodel.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Client is the resolver for the client field.
func (r *queryResolver) Client(ctx context.Context, id string) (*dbmodel.Client, error) {
	panic(fmt.Errorf("not implemented: Client - client"))
}

// Clients is the resolver for the clients field.
func (r *queryResolver) Clients(ctx context.Context, filter *graphmodel.ClientFilterInput, pagination *graphmodel.PaginationInput) ([]*dbmodel.Client, error) {
	panic(fmt.Errorf("not implemented: Clients - clients"))
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*dbmodel.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversation - conversation"))
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context, filter *graphmodel.ConversationFilterInput, pagination *graphmodel.PaginationInput) ([]*dbmodel.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversations - conversations"))
}

// Email is the resolver for the email field.
func (r *queryResolver) Email(ctx context.Context, id string) (*dbmodel.Email, error) {
	panic(fmt.Errorf("not implemented: Email - email"))
}

// Emails is the resolver for the emails field.
func (r *queryResolver) Emails(ctx context.Context, filter *graphmodel.EmailFilterInput, pagination *graphmodel.PaginationInput) (*graphmodel.EmailConnection, error) {
	panic(fmt.Errorf("not implemented: Emails - emails"))
}

// EmailTemplate is the resolver for the emailTemplate field.
func (r *queryResolver) EmailTemplate(ctx context.Context, id string) (*dbmodel.EmailTemplate, error) {
	panic(fmt.Errorf("not implemented: EmailTemplate - emailTemplate"))
}

// EmailTemplates is the resolver for the emailTemplates field.
func (r *queryResolver) EmailTemplates(ctx context.Context) ([]*dbmodel.EmailTemplate, error) {
	panic(fmt.Errorf("not implemented: EmailTemplates - emailTemplates"))
}

// NewMessage is the resolver for the newMessage field.
func (r *subscriptionResolver) NewMessage(ctx context.Context, conversationID string) (<-chan *dbmodel.Message, error) {
	panic(fmt.Errorf("not implemented: NewMessage - newMessage"))
}

// ConversationUpdated is the resolver for the conversationUpdated field.
func (r *subscriptionResolver) ConversationUpdated(ctx context.Context, conversationID string) (<-chan *dbmodel.Conversation, error) {
	panic(fmt.Errorf("not implemented: ConversationUpdated - conversationUpdated"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *dbmodel.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *dbmodel.User) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *dbmodel.User) (*graphmodel.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Client returns generated.ClientResolver implementation.
func (r *Resolver) Client() generated.ClientResolver { return &clientResolver{r} }

// Conversation returns generated.ConversationResolver implementation.
func (r *Resolver) Conversation() generated.ConversationResolver { return &conversationResolver{r} }

// ConversationParticipant returns generated.ConversationParticipantResolver implementation.
func (r *Resolver) ConversationParticipant() generated.ConversationParticipantResolver {
	return &conversationParticipantResolver{r}
}

// Email returns generated.EmailResolver implementation.
func (r *Resolver) Email() generated.EmailResolver { return &emailResolver{r} }

// EmailAttachment returns generated.EmailAttachmentResolver implementation.
func (r *Resolver) EmailAttachment() generated.EmailAttachmentResolver {
	return &emailAttachmentResolver{r}
}

// EmailTemplate returns generated.EmailTemplateResolver implementation.
func (r *Resolver) EmailTemplate() generated.EmailTemplateResolver { return &emailTemplateResolver{r} }

// Message returns generated.MessageResolver implementation.
func (r *Resolver) Message() generated.MessageResolver { return &messageResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type clientResolver struct{ *Resolver }
type conversationResolver struct{ *Resolver }
type conversationParticipantResolver struct{ *Resolver }
type emailResolver struct{ *Resolver }
type emailAttachmentResolver struct{ *Resolver }
type emailTemplateResolver struct{ *Resolver }
type messageResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
